name: main

on:
    push:
      branches: [ "main" ] # Triggers on pushes to main
      tags: [ "v*" ] # Triggers on any tag with the prefix 'v'
    pull_request:
      branches: [ "main" ] # Triggers on pull requests
# Create a strategy matrix and define the runner systems there

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [ 
            {name: linux, os: ubuntu-latest,},
            {name: windows, os: windows-latest,},
            ]
    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.5

      - name: Build
        run: make r system=${{ matrix.build.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SkyDriver-${{ matrix.build.name }}
          path: ./build/SkyDriver-${{ matrix.build.name }}*

  Release:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/SkyDriver*
          generate_release_notes: true
